version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11rc2
    working_directory: /go/src/ekyu.moe/cryptonight
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run:
          name: preprocess
          command: go generate ekyu.moe/cryptonight/...
      - run:
          name: gofmt
          command: diff -u <(echo -n) <(gofmt -d .)
      - run:
          name: govet
          command: go vet ./...
      - run:
          name: test and coverage
          command: |
            go test -v -coverprofile=coverage.txt -covermode=set -timeout=30m &&
            bash <(curl -s https://codecov.io/bash)
      - run:
          name: benchmark
          command: |
            sed -nr '/model name/ s/.*:\s*(.*) @ .*/\1/p' /proc/cpuinfo;
            go test -v -bench=. -benchmem
